Fix TypedDict import for Python < 3.12 compatibility
Change from typing.TypedDict to typing_extensions.TypedDict
to fix Pydantic error on Python 3.11.

Error: Please use `typing_extensions.TypedDict` instead of
`typing.TypedDict` on Python < 3.12.